### ISSUE TITLE
Doesn't work when not in the Gemfile

### ISSUE THREAD

**Issue by darthdeus** [jonleighton/spring-commands-rspec#16]
I might be doing something wrong, but I've tried running `spring rspec spec` in a project that doesn't have spring in its Gemfile and I'm getting `The 'rspec' command is not known to spring.`.

If I add both to a Gemfile, generate binstubs and then run `./bin/spring rspec spec` everything works as expected.

Is this expected or am I doing something wrong?

**Comment by jakswa** [comment]
Just wanted to give a big thanks for this. For some reason, this took me forever to hunt down, when following the ["using without adding to bundle"](https://github.com/rails/spring#use-without-adding-to-bundle) flow for Spring. I'd love to either add a reference to this configuration in this gem's README, or maybe in Spring's README if that makes more sense. Just to help anyone else who can't add spring to their Gemfile.

In any case, +1 for this.
